### ISSUE TITLE
[BUG] Crash on adding new medication, 1.4.0

### ISSUE THREAD

**Issue by GitGitro** [waseefakhtar/dose-android#140]
The app crashes when trying to add a new medication, I'll try to solve this asap as is kinda huge as crash. here is the log

```
FATAL EXCEPTION: main      
Process: com.waseefakhtar.doseapp, PID: 26115
android.content.res.Resources$NotFoundException: Plural resource ID #0x7f0b0000 quantity=4 item=other
at android.content.res.ResourcesImpl.getQuantityText(ResourcesImpl.java:321)
at android.content.res.Resources.getQuantityText(Resources.java:529)
at android.content.res.Resources.getQuantityString(Resources.java:605)
at androidx.compose.ui.res.StringResources_androidKt.pluralStringResource(StringResources.android.kt:91)
...
```

**Comment by waseefakhtar** [comment]
Great catch @GitGitro! 👏
