### ISSUE TITLE
Selecting a date less than today crashes the application

### ISSUE THREAD

**Issue by Wottrich** [waseefakhtar/dose-android#84]
# Video
 
https://github.com/waseefakhtar/dose-android/assets/24254062/42bb8cc6-5491-4880-826c-5c49be1ea7d5

# Crash
```
Process: com.waseefakhtar.doseapp, PID: 10200
                                                                                                    java.util.NoSuchElementException: List is empty.
                                                                                                    	at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:214)
                                                                                                    	at com.waseefakhtar.doseapp.feature.medicationconfirm.MedicationConfirmRouteKt.MedicationConfirmScreen(MedicationConfirmRoute.kt:101)
                                                                                                    	at com.waseefakhtar.doseapp.feature.medicationconfirm.MedicationConfirmRouteKt.MedicationConfirmRoute(MedicationConfirmRoute.kt:46)
                                                                                                    	at com.waseefakhtar.doseapp.feature.medicationconfirm.navigation.MedicationConfirmDestinationKt$medicationConfirmGraph$1.invoke(MedicationConfirmDestination.kt:31)
                                                                                                    	at com.waseefakhtar.doseapp.feature.medicationconfirm.navigation.MedicationConfirmDestinationKt$medicationConfirmGraph$1.invoke(MedicationConfirmDestination.kt:24)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:138)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.navigation.compose.NavHostKt$NavHost$14$1.invoke(NavHost.kt:320)
                                                                                                    	at androidx.navigation.compose.NavHostKt$NavHost$14$1.invoke(NavHost.kt:318)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:248)
                                                                                                    	at androidx.compose.runtime.saveable.SaveableStateHolderImpl.SaveableStateProvider(SaveableStateHolder.kt:84)
                                                                                                    	at androidx.navigation.compose.NavBackStackEntryProviderKt.SaveableStateProvider(NavBackStackEntryProvider.kt:65)
                                                                                                    	at androidx.navigation.compose.NavBackStackEntryProviderKt.access$SaveableStateProvider(NavBackStackEntryProvider.kt:1)
                                                                                                    	at androidx.navigation.compose.NavBackStackEntryProviderKt$LocalOwnersProvider$1.invoke(NavBackStackEntryProvider.kt:52)
                                                                                                    	at androidx.navigation.compose.NavBackStackEntryProviderKt$LocalOwnersProvider$1.invoke(NavBackStackEntryProvider.kt:51)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                                                                                                    	at androidx.navigation.compose.NavBackStackEntryProviderKt.LocalOwnersProvider(NavBackStackEntryProvider.kt:47)
                                                                                                    	at androidx.navigation.compose.NavHostKt$NavHost$14.invoke(NavHost.kt:318)
                                                                                                    	at androidx.navigation.compose.NavHostKt$NavHost$14.invoke(NavHost.kt:302)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:138)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.animation.AnimatedContentKt$PopulateContentFor$5.invoke(AnimatedContent.kt:942)
                                                                                                    	at androidx.compose.animation.AnimatedContentKt$PopulateContentFor$5.invoke(AnimatedContent.kt:933)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:117)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.animation.AnimatedVisibilityKt.AnimatedEnterExitImpl(AnimatedVisibility.kt:818)
                                                                                                    	at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6$2$1.invoke(AnimatedContent.kt:1256)
                                                                                                    	at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6$2$1.invoke(AnimatedContent.kt:824)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6.invoke(AnimatedContent.kt:855)
                                                                                                    	at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6.invoke(AnimatedContent.kt:775)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:117)
2023-10-16 20:45:38.020 10200-10200 AndroidRuntime          com.waseefakhtar.doseapp             E  	at androidx.compose.runtime.internal.ComposableLambdaImpl$invoke$1.invoke(ComposableLambda.jvm.kt:129)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl$invoke$1.invoke(ComposableLambda.jvm.kt:128)
                                                                                                    	at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:192)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2531)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.skipToGroupEnd(Composer.kt:2823)
                                                                                                    	at androidx.compose.ui.layout.LookaheadScopeKt.LookaheadScope(LookaheadScope.kt:66)
                                                                                                    	at androidx.compose.animation.AnimatedContentKt.AnimatedContent(AnimatedContent.kt:775)
                                                                                                    	at androidx.navigation.compose.NavHostKt.NavHost(NavHost.kt:280)
                                                                                                    	at androidx.navigation.compose.NavHostKt.NavHost(NavHost.kt:129)
                                                                                                    	at com.waseefakhtar.doseapp.navigation.DoseNavHostKt.DoseNavHost(DoseNavHost.kt:27)
                                                                                                    	at com.waseefakhtar.doseapp.ComposableSingletons$DoseAppKt$lambda-2$1$2.invoke(DoseApp.kt:112)
                                                                                                    	at com.waseefakhtar.doseapp.ComposableSingletons$DoseAppKt$lambda-2$1$2.invoke(DoseApp.kt:101)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:117)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl$invoke$1.invoke(ComposableLambda.jvm.kt:129)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl$invoke$1.invoke(ComposableLambda.jvm.kt:128)
                                                                                                    	at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:192)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2531)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2800)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3281)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:3232)
                                                                                                    	at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:934)
                                                                                                    	at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:1143)
                                                                                                    	at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:124)
                                                                                                    	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:580)
                                                                                                    	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:548)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:41)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:970)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:727)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loop(Looper.java:223)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7656)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@b79033d, androidx.compose.ui.platform.MotionDurationScaleImpl@fb12732, StandaloneCoroutine{Cancelling}@b0b1c83, AndroidUiDispatcher@6bd3e00]
```

**Comment by Wottrich** [comment]
@waseefakhtar Can you assign me to this issue? I will fix it

**Comment by waseefakhtar** [comment]
> @waseefakhtar Could you please assign me to this issue? I will fix it, if you want

Sure, go ahead!
